@echo off
setlocal EnableDelayedExpansion

set CMAKE_ARGS_EXTRA=

REM --- GPU selection ---
if "%gpu_variant:~0,5%"=="cuda-" (
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DWITH_CUDA=ON -DWITH_CUDNN=ON -DCUDA_DYNAMIC_LOADING=ON
) else (
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DWITH_CUDA=OFF -DWITH_CUDNN=OFF
)

REM --- BLAS selection ---
if "%blas_impl%"=="mkl" (
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DWITH_MKL=ON -DWITH_OPENBLAS=OFF -DWITH_ACCELERATE=OFF
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DOPENMP_RUNTIME=INTEL
) else if "%blas_impl%"=="openblas" (
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DWITH_MKL=OFF -DWITH_OPENBLAS=ON -DWITH_ACCELERATE=OFF
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DOPENMP_RUNTIME=COMP
) else if "%blas_impl%"=="cublas" (
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DWITH_MKL=OFF -DWITH_OPENBLAS=OFF -DWITH_ACCELERATE=OFF
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DOPENMP_RUNTIME=COMP
) else (
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DWITH_MKL=OFF -DWITH_OPENBLAS=OFF -DWITH_ACCELERATE=OFF
    set CMAKE_ARGS_EXTRA=!CMAKE_ARGS_EXTRA! -DOPENMP_RUNTIME=COMP
)

cmake -S . -B build ^
    -G Ninja ^
    %CMAKE_ARGS% ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DBUILD_SHARED_LIBS=ON ^
    -DBUILD_CLI=OFF ^
    -DBUILD_TESTS=OFF ^
    -DENABLE_CPU_DISPATCH=ON ^
    -DWITH_DNNL=OFF ^
    -DWITH_RUY=OFF ^
    !CMAKE_ARGS_EXTRA!
if errorlevel 1 exit 1

cmake --build build --config Release --verbose
if errorlevel 1 exit 1

cmake --install build
if errorlevel 1 exit 1
